### ISSUE TITLE
Tolle LIB - Weitere Services

### ISSUE THREAD

**Issue by PatrickSchmidtSE** [Kruemelino/FBoxAPI#1]
Tolle LIB , vielen Dank für die Mühe!

Aktuell fehlen mir noch ein paar Services (UserSCDP für die Update Info , RemoteSCDP für DynDNS und Wanpppconn1 bzw Wanipconn1  ,weil bei manchen Boxen die WanCommonConfig nichts liefert).

Aber ansonsten super Basis. Wäre es nicht VB , würde ich die Services wahrscheinlich auch selbst implementieren.

Wenn du die LIB übrigens in C# Kontext nutzt gibt es noch Probleme mit deinen Klassen, wie DeviceInfo. Die Properties sind dort nämlich nicht public und somit nicht zugreifbar.

Das nur als ein paar Notizen :)

**Comment by Kruemelino** [comment]
Ich würde mal behaupten, dass ich das Thema mit dem Public anpassen kann.

Ja mir ist es bewusst: ich bin VB versaut. Ich hab es versucht mit C#. Machbar wäre es sicher.

Fehlende Services kann ich natürlich auch hinzufügen. So ist ja auch der Plan. Nur an der Zeit fehlt es manchmal :D

**Comment by PatrickSchmidtSE** [comment]
Alles gut :) Das waren ja nur Hinweise und Einschränkungen bezogen auf c# (was die meisten sicher benutzen). 
Dann würde deine LIB sicher noch einfacher genutzt werden können!

**Comment by Kruemelino** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/4273483/149276030-9b9a8f9e-20cf-46d8-a3b5-c50bab0e8a46.png">

Hast du mal geprüft, ob dieser Tippfehler nur in der Doku ist?

**Comment by PatrickSchmidtSE** [comment]
Nein, diese Komponente musste ich nie nutzen für meine Zwecke :)

**Comment by Kruemelino** [comment]
Ich habe mal eine nicht ganz uneigennützige Frage:

Da ich mich mit C# nicht so auskenne, würdest du mich bei der Umstellung unterstützen?
Ich habe es mal im Visual Studio umwandeln lassen, jedoch wird das Ergebnis nicht Optimal sein.

**Comment by PatrickSchmidtSE** [comment]
Ich bin mittlerweile auf die PS.Fritzbox.API umgestiegen, weil ich nicht soviel Zeit hatte für das Projekt :/ Sorry, trotzdem danke!

**Comment by Kruemelino** [comment]
Ok. Vielleicht ergibt sich ja mal die Gelegenheit. Viel Erfolg!
