### ISSUE TITLE
GetHostList Aktion im Hosts service funktioniert nicht wie erwartet

### ISSUE THREAD

**Issue by RoSchmi** [Kruemelino/FBoxAPI#2]
Ich beschäftige mich gerade mit dem Hosts service und die 'GetHostNumberOfEntries' und 'GetHostListPath' funtionieren mit der letzten API Version.
Bei der 'GetHostList' Aktion wird mir allerdings eine leere HostList zurückgeliefert. Mache ich etwas falsch?

`HostList hostList = new HostList();`
`if (fritzBoxTR64.Hosts.GetHostList(ref hostList))`
`{
        var copyHostList = hostList;
}

else

{
        HostList theCopy = hostList;
} `

**Comment by Kruemelino** [comment]
Grundsätzlich machst du alles richtig.
Ich bin davon ausgegangen, dass in `GetHostListPath` der komplette Pfad zum Script ausgegeben wird. Stattdessen wird nur `/devicehostlist.lua?sid=97ebd547080a032a` ausgegeben. 
Es ist nach meiner Meinung mal wieder eine Ungenauigkeit in der Doku.
> Related path to lua script which generates a formatted list

Mal macht es AVM so und mal so. 

Ich passe die Funktion an.

**Comment by RoSchmi** [comment]
Hallo,
Danke für die schnellen Korrekturen.
Aber immer noch kehrt die Aktion mit 'false' zurück, obwohl die gewünschten Daten in 'HostEntry' übernommen wurden.
`HostEntry hostEntry = null;`
`var theResult = true;`
`theResult = fritzBoxTR64.Hosts.GetGenericHostEntry(10, ref `hostEntry);`

**Comment by Kruemelino** [comment]
Der gleiche Fehler wie zuvor. 'Convert.ChangeType' kann die Strings "0" und "1" nicht in Boolean umwandeln.

**Comment by RoSchmi** [comment]
Funktioniert jetzt mit der letzten Version. Danke.

**Comment by Kruemelino** [comment]
Super. Freut mich!
Wenn was sein sollte, dann mach einfach ein Issue auf. Ich schau es mir an. Auch wenn du meist, dass irgendetwas vielleicht vielleicht anders gelöst werden soll, dann bin ich gerne bereit mir das anzuschauen.

Ich habe heute die letzten fehlenden Services zusammengestellt. Mir Ausnahme der IDG sind nun alle vorhanden.
