### ISSUE TITLE
Setzen einer festen IP per MAC / Löschen von Hosts aus bekannten Geräten

### ISSUE THREAD

**Issue by Paddy3911** [Kruemelino/FBoxAPI#5]
Hi!
Ich kriege es leider nicht hin eine feste IP für eine bestimmte MAC-Adresse zu vergeben. Hat hier jemand einen Ansatz wie ich vorgehen muss?

`   Try

       Dim Anmeldeinformationen As New Net.NetworkCredential(fb_user, fb_password)
       Using FBoxTR064 As New FBoxAPI.FritzBoxTR64(fb_ip, Anmeldeinformationen)

           With FBoxTR064.Deviceconfig

               ' Action ausführen
               If .GetSessionID(SessionID) Then
                   FBoxTR064.Hosts.set?? 
               Else

               End If
           End With
       End Using
   Catch ex As Exception

   End Try`
   
   Auch wäre es richtig cool, wenn ich nicht genutzte Hosts per Mac löschen kann. 
   
   Vielen Dank und Grüße :)

**Comment by Kruemelino** [comment]
Ich hab gerade mal nachgeschaut. Es gibt keine TR-064 Aktionen, die deine gewünschten Ziele erreichen.
